spring.application.name=hr-system

# =========================
# Profile
# =========================
spring.profiles.active=local

# =========================
# JPA
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# =========================
# Logging
# =========================
logging.level.root=INFO
logging.level.com.portfolio.hr_system=DEBUG

logging.file.name=logs/hr-system.log

logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7

# =========================
# Swagger
# =========================
springdoc.swagger-ui.path=/swagger-ui.html